- gremlin/templates/_helpers.tpl
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Add [apparmor
profile](https://kubernetes.io/docs/tutorials/clusters/apparmor/) to the
Gremlin DaemonSet. The behavior of this apparmore profile is as follows:
1. Use the profile specified by `apparmorOverride` if present
2. Otherwise, use `apparmor: runtime/default` if `gremlin.hostPID
== false`, or `unconfined` if `gremlin.hostPID == true`
> AGENT-100: Add apparmor profile to DaemonSet config

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
This was using `gremlin.fullname` helper value, which works as long as the full name is overridden such that the container name matches but fails otherwise.
> Use .Chart.Name for apparmor

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/_helpers.tpl
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
A recent change broke the Gremlin Helm Chart for systems that did not
have apparmor. This change modify's this chart's behavior such that the
new apparmor annotation is applied only when the user supplies `--set
gremlin.apparmor=...`.
While this means we don't set apparmor to the exact profile Gremlin
desires, we allow it to be configurable enough to work for systems with
and without apparmor.
In a later change, I propose we do the same for SELinux, and
automatically set proper values based on some discovery of what the
system supports. We'll start with user input first.
> AGENT-183: Use gremlin.apparmor only when supplied by user input

- gremlin/templates/daemonset.yaml
Deploying this chart caused this error:
unknown field "name" in io.k8s.api.core.v1.PodSpec
Removing the name field fixes this.
> Fix invalid PodSpec by removing name field

- gremlin/README.md
- gremlin/templates/secret.yaml
- gremlin/values.yaml
The Helm chart currently relies on a manually created Kubernetes Secret to store the client key and cert files.  In some cases it can be easier to supply Helm with the relevant key materials and allow it to create the Secret.
This PR maintains the previous default functionality where a manually created Secret is expected.  However, there is a new option where Helm can be provided with `certContent` and `keyContent` so it can create the Secret for you.
Template out the chart with the default values.yaml
```
helm template gremlin/
```
Ensure things look as expected.
Put a gremlin key and cert in the local directory.  Template out the chart with the new options set and ensure they look as expected.
```
helm template gremlin/ --set gremlin.client.certCreateSecret=true --set-file …
```
> Add support for a Helm managed Secret

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/chao-service-account.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Add a deployment and supporting resources for managing a gremlin
kubernetes client. The client is installed by default but may be
disabled by setting `gremlin.installK8sClient=false`
> Install kubernetes client by default

- README.md
- gremlin/README.md
- gremlin/templates/_helpers.tpl
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
- gremlin/templates/secret.yaml
- gremlin/values.yaml
This PR consolidates all existing ways to configure Gremlin into the following helm values
```
gremlin.secret.managed     = true|false
gremlin.secret.type        = secret|certificate
gremlin.secret.name        = name of external k8s secret
gremlin.secret.clusterID   = YOUR-CLUSTER-ID
gremlin.secret.teamID      = YOUR-TEAM-ID
gremlin.secret.teamSecret  = YOUR-TEAM-SECRET
gremlin.secret.certificate = /path/to/cert
gremlin.secret.key         = /path/to/key
```
For an externally managed secret, only `managed`, `type`, and `name` are required. Other values can be supplied as overrides (e.g. `clusterID` and `teamID`)
> Refactor gremlin values to support cert+secrets

- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Add support for setting container resources. 
Helm Client Version: 2.13.1
Expected format in values.yml is:
```
resources:  
limits:
memory: xMi
requests:
cpu: ym
memory: zMi
```
Helm Template output:
```
apiVersion: v1
kind: ServiceAccount
metadata:
name: chao
namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: gremlin-watcher
rules:
- apiGroups: ["apps"]
resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
verbs: ["get", "watch", "list"]
- apiGroups: [""]
resources: ["pods", "nodes"]
verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: chao
subjects:
- kind: ServiceAccount
name: chao
namespace: default
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: …
```
> Add support for setting resources

- gremlin/Chart.yaml
- gremlin/values.yaml
**Background**
Gremlin has been using capabilities provided by default: `CAP_SYS_CHROOT` and `CAP_NET_RAW`.
Newer versions of Crio and/or OpenShift have changed the default capabilities provided to new containers. Two capabilities Gremlin needs were dropped:
* CAP_NET_RAW (gremlin technically doesn't need this but it does request it, see https://gremlininc.atlassian.net/browse/EN-561)
* CAP_SYS_CHROOT (required to create and enter namespaces of our sidecars)
**Change**
* add declaration for the above needed caps
**Testing**
* Create a kubernetes environment (e.g. ` minikube start --container-runtime=crio`)
* Install Gremlin according to [our documentation][criodoc]
* Run an attack against a pod or container
Observe attack successfully starts where it previously failed without this change. …
> add required capabilities SYS_CHROOT and NET_RAW

- gremlin/README.md
change 'tolerations[0].operation=Exists' to 'tolerations[0].operator=Exists'
> EN-712 incorrect syntax for enabling master node

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
- gremlin/templates/secret-ssl-cert-file.yaml
- gremlin/values.yaml
**Background**
Gremlin can be configured to communicate with api.gremlin.com through an http_proxy (See [documentation][proxydocs]). The Gremlin Helm chart exposes no mechanism for configuring Gremlin to use such a proxy.
**Change**
* create a new value `gremlin.proxy.url` whose default is `""`
* modify `daemonset.yaml` and `chao-deployment.yaml` to set `http_proxy` and `no_proxy` environment variables when this value is non-blank
**Testing**
* spun up Gremlin on `minikube` with and without proxy settings
```shell
helm install gremlin ./gremlin \
--namespace gremlin \
--set      gremlin.secret.managed=true \
--set      gremlin.secret.clusterID=test \
--set      gremlin.secret.teamID=$GREMLIN_TEAM_ID \
--set-file gremlin.secret.certificate=$PATH_TO_CERTIFICATE \
--set-file …
```
> expose gremlin.proxy.url to configure Gremlin with http_proxy

- gremlin/Chart.yaml
- gremlin/values.yaml
**Background**
This fixes issue #40
**Change**
Add a default level of `s0-s0:c0.c1023` which is permissive enough to grant `gremlin.process` access to read all files permitted by https://github.com/selinux-policies/.
> add level to SELinux options to address errors during attacks

- gremlin/Chart.yaml
This change moves our latest helm chart release out of pre-release and into GA. It includes
https://github.com/gremlin/helm/pull/46
> move 0.4.0 out of pre-release

- gremlin/Chart.yaml
- gremlin/templates/gremlin-psp.yaml
- gremlin/values.yaml
* When `seccomp` and `podSecurityPolicy` flags are both enabled, Gremlin fails to install because the `initContainer` responsible for setting up the seccomp policy, is constrained to using only the policy it is trying to set up, producing a chicken and egg scenario.
* Add `runtime/default` (already advertised as the `defaultProfileName` in our PSP) to the list of `allowedProfileNames`, which enables our `initContainer` to assume it so it can set up the `localhost/gremlin` profile assumed by our main `gremlin` container.
* Local testing shows success with a PSP enabled cluster
```shell
minikube start \
--extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy \
--addons=pod-security-policy \
--kubernetes-version=v1.19.1
helm install gremlin ./gremlin \
--namespace gremlin \
--set …
```
> allow default seccomp profile to fix seccomp+PSP installs

- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Introduce `affinity`, `nodeSelector`, and `tolerations` to the Chao deployment chart.  See https://gremlininc.slack.com/archives/C010HA9NQK1/p1633649317296600 for more details.
> add-affinity-nodeselector-tolerations-to-chao

- gremlin/templates/daemonset.yaml
Gremlin needs write access to `/sys/fs/cgroup` so that we can place Gremlin attack sidecars into the cgroup of our targets.
> cgroupv2 support: allow /sys/fs/cgroup to be writable

- gremlin/Chart.yaml
- gremlin/values.yaml
`gremlind v2.26.0` will not need this capability
> remove unused capability: SYS_RESOURCE

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
This has been defaulted to `true` in `gremlin 2.25.0`. This helm chart change is made to match this.
> enable gremlin process collection by default

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Allows the user to specify SELinux labels and types to apply to the Gremlin Daemonset.
Also bumps chart to `0.8.0`.
NOTE: These are exceptionally dangerous options and customers using them may negatively impact their cluster or Gremlin deployment in ways that Gremlin cannot support
> [Gremlin Agent] Provide SeLinuxOptions for overriding

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
**Background**
We want to provide some convenience around users being able to add labels to the deployed Gremlin Pods
**Change**
Add labels to `values.yaml` and then apply them to the associated Deployment/DaemonSet
I've applied them to both the Pod and the managing K8s primitive, but I can be convinced to only put them on the Pod
> [Labels] Add Overridable Labels

- gremlin/Chart.yaml
- gremlin/values.yaml
* when set `gremlin.container.driver=any` will attempt to mount all possible container driver paths, delegating to `gremlin` to pick the runtime. This option has served as the easiest way to get Gremlin up and running on containerized systems because you don't need to know or muck with container driver details.
* make `any` the new default
> make gremlin.container.driver=any the new default

- gremlin/Chart.yaml
- gremlin/values.yaml
Certificate expiry experiments with CIDRs are failing due to a permission error when reading the sockets of a process.
Add the linux capability `DAC_READ_SEARCH` to enable this.
> Add DAC_READ_SEARCH for CIDR cert expiry tests

- gremlin/agent_apparmor.profile
If a cert expiry experiment is configured to target a CIDR, the linux capabilities `dac_read_search` and `sys_ptrace` are required to discover the active connections that match that CIDR.
Update a comment to clarify that we need those capabilities for service discovery (in `gremlind`) but also certificate expiry experiments (in `gremlin`).
> Clarify the capabilities for cert expiry

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
- gremlin/values.yaml
Added option to enable new DNS collection feature. By default it will be off.
New lines were added in the same place the current process collection config exists.
```
zach@DESKTOP-GIU9M5L:/mnt/c/Users/Zach/My Documents/Workspace/helm$ helm template gremlin ./gremlin --set gremlin.collect.dns=true --set gremlin.secret.type=secret --set gremlin.secret.teamSecret=secret --set gremlin.secret.managed=true --set gremlin.secret.teamID=test --set gremlin.secret.clusterID=cluseter
...
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: gremlin
namespace: default
labels:
app.kubernetes.io/name: gremlin
helm.sh/chart: gremlin-0.12.1
app.kubernetes.io/instance: gremlin
app.kubernetes.io/managed-by: Helm
version: v1
spec:
selector:
matchLabels:
app.kubernetes.io/name: gremlin
updateStrategy: …
```
> Add DNS collection configuration

- gremlin-integrations/templates/_helpers.tpl
- gremlin/Chart.yaml
- gremlin/templates/_helpers.tpl
- gremlin/values.yaml
There was a bug where helm inaccurately assumed the type of the certificate field
```
Helm upgrade failed for release gremlin/gremlin with chart gremlin@0.12.2: template: gremlin/templates/daemonset.yaml:111:50: executing "gremlin/templates/daemonset.yaml" at <.Values.gremlin.secret.certificate>: wrong type for value; expected string; got interface {}
```
So I set the default in values.yaml to be empty strings
Test:
```
helm template gremlin ./gremlin  --namespace gremlin  --set gremlin.secret.name=gremlin-secret  --set gremlin.secret.type=certificate  --set gremlin.secret.clusterID="cluster-id"  --set gremlin.secret.teamID="team-id"
...
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: gremlin
namespace: gremlin
labels:
app.kubernetes.io/name: gremlin
helm.sh/chart: gremlin-0.12.3 …
```
> Fix string type values

- gremlin-integrations/Chart.yaml
- gremlin-integrations/templates/deployment.yaml
- gremlin-integrations/values.yaml
- gremlin/Chart.yaml
- gremlin/templates/chao-deployment.yaml
- gremlin/templates/daemonset.yaml
* A recent change broke secret references for both secret auth and certificate auth.
* Regression introduced in #88
* Fix for secret auth introduced in #92
* Account for `.Values.gremlin.secret.managed` when populating values for `GREMLIN_TEAM_CERTIFICATE_OR_FILE` and `GREMLIN_TEAM_PRIVATE_KEY_OR_FILE`
**Setup**
Create Secret
```shell
kubectl create secret generic my-gremlin-secret \
--namespace gremlin \
--from-literal=GREMLIN_TEAM_ID=$GREMLIN_TEAM_ID \
--from-file=gremlin.cert=/path/to/cert.pem \
--from-file=gremlin.key=/path/to/key.pem \
--from-literal=GREMLIN_CLUSTER_ID=my-cluster-id
```
Install Gremlin
```shell
helm install gremlin gremlin/gremlin \
--namespace gremlin \
--set gremlin.secret.name=my-gremlin-secret \
--set gremlin.secret.type=certificate
```
**Without fix**
Gremlin …
> correctly ref cert paths when gremlin.secret.managed=false

- gremlin/Chart.yaml
- gremlin/values.yaml
We're going to be enabling DNS collection by default soon, so staging this PR for when the agent change is ready to release.
> Switch default values of gremlin.collect.processes/dns

- gremlin/Chart.yaml
- gremlin/values.yaml
We need the linux capability `SYS_RESOURCE` for process exhaustion attacks to safeguard against lingering defunct processes after an out of memory error.
Add the linux capability `SYS_RESOURCE` for updating the OOM score of the `gremlin` process.
> Add cap SYS_RESOURCE for Process Exhaustion container attacks

- gremlin/Chart.yaml
- gremlin/templates/_helpers.tpl
- gremlin/values.yaml
* Added new Linux container drivers as options
- docker-linux
- containerd-linux
- crio-linux
- linux (any for -linux)
* Set default container driver to `linux`
* Bumped version
```
volumeMounts:
- name: gremlin-state
mountPath: /var/lib/gremlin
readOnly: false
- name: gremlin-logs
mountPath: /var/log/gremlin
readOnly: false
- name: cgroup-root
mountPath: /sys/fs/cgroup
readOnly: false
- name: shutdown-trigger
mountPath: /sysrq
- name: containerd-sock
mountPath: /run/containerd/containerd.sock
readOnly: true
- name: containerd-runc
mountPath: /run/containerd/runc/k8s.io
readOnly: false
- name: crio-sock
mountPath: /run/crio/crio.sock
readOnly: true
- name: crio-runc
mountPath: /run/runc
readOnly: false
- name: docker-sock
mountPath: /var/run/docker.sock
readOnly: true
- name: docker-runc …
```
> Add new linux drivers for container driver

- gremlin/agent_apparmor.profile
Add linux capability `sys_resource` for process exhaustion to change the oom score of the `gremlin` process.
> Add capability for process exhaustion

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
- gremlin/templates/gremlin-scc.yaml
- gremlin/values.yaml
* scc fields fsGroup and supplementalGroups are exposed in Kubernetes PodSecurityPolicies, not SecurityContextConstraints. You can see warnings for these fields when installing Gremlin into OpenShift 4.14.
* Gremlin sets an seLinux.type value in its scc implying Gremlin will run as `gremlin.process`. In reality, CRI-O does not allow running containers that have `hostPID=true` under any SELinux label other than spc_t`. See https://github.com/cri-o/cri-o/blob/main/server/container_create_linux.go#L306 and https://github.com/cri-o/cri-o/issues/5501.
* remove `fsGroup` and `supplementalGroups` from gremlin-scc.yaml (they are invalid)
* rename seLinux.type under the scc section to use `spc_t` instead of `gremlin.process`
* explicitly pass `allowPrivilegeEscalation` to our daemonset, already …
> cleanup: remove invalid scc field, clarify SELinux constraint

- gremlin/Chart.yaml
- gremlin/templates/gremlin-service-account.yaml
Gremlin daemon needs permissions to fetch the zone and region from the K8s node's topology labels in case they are available in on-prem clusters or clusters not hosted in AWS, GCP or Azure.
Add a cluster role binding to grant access to the cluster's node labels.
- Verified the gremlin's tags `zone` and `region` are populated with the node's `topology.kubernetes.io/zone` and `topology.kubernetes.io/region` labels in an Openshift cluster after installing this chart
- Verified that the daemon logs a permission warning about checking the helm chart after installing an older version of this chart
> Grant access to K8s zone and region labels

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
* When `gremlin.podSecurity.createSecurityContextConstraints.create=true` we create a `gremlin` scc, but do not force the pods of the gremlin daemonset to run with it
* Forcing pods to use this scc requires an annotation: https://docs.openshift.com/container-platform/4.14/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
* set `openshift.io/require-scc: gremlin` when scc creation is enabled
> openshift: annotate require-scc on daemonset to force our scc

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/agent_apparmor.profile
- gremlin/templates/daemonset.yaml
- gremlin/templates/gremlin-psp.yaml
- gremlin/values.yaml
* Gremlin currently allows a host shutdown in two different ways: using a `/proc/sysrq-trigger`, and issuing a shutdown from the host's `PID` namespace. Only the latter [is documented](https://www.gremlin.com/docs/fault-injection-experiments-shutdown), and the former performs a non-graceful shutdown (which isn't documented in Gremlin).
* At the same time, `hostPID=true` has become a requirement for all container drivers except for the legacy `docker` driver. It makes sense to flip this to `true` to minimize issues at install time resulting from incorrect arguments.
* `hostNetwork` is in the same situation, though unrelated to shutdown attacks.
* Remove mount of `/proc/sysrq-trigger` which disables this functionality in Gremlin
* default `hostPID=true` to enable host attacks without sysrq …
> remove /proc/sysrq-trigger mount, default host namespaces true

- gremlin/Chart.yaml
- gremlin/templates/daemonset.yaml
* We expose `gremlin.podSecurity.privileged` in our values.yaml, but never use it
* Set the daemonset's `privileged` value according to values
> reference privileged value in daemonset.yaml to honor user input

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/chao-deployment.yaml
- gremlin/values.yaml
The chao agent can accept an argument to limit the targeting of namespaces watched and uploaded. This change exposes that argument more easily in the helm chart.
```
helm template gremlin ./gremlin --namespace gremlin --set gremlin.hostPID=true --set gremlin.hostNetwork=true --set gremlin.collect.processes=true --set gremlin.container.driver=docker-runc --set gremlin.secret.managed=true --set gremlin.secret.type=secret --set gremlin.secret.teamID=a --set gremlin.secret.teamSecret=b --set gremlin.serviceUrl=c --set image.tag=$(git rev-parse HEAD) --debug --set chao.namespaces[0]=x --set chao.namespaces[1]=y --set chao.namespaces[2]=z
......
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/instance: chao
app.kubernetes.io/name: chao
helm.sh/chart: gremlin-0.18.0 …
```
> Add namespaces argument for chao

- gremlin/Chart.yaml
- gremlin/templates/chao-service-account.yaml
Add permissions so that Argo rollouts can be targeted (agent changes are still needed).
Added RBAC rules for `argoproj.io` API group to allow `get`, `list`, and `watch` verbs on `rollouts` resource.
> [Rollout] Add permissions for Argo Rollouts

- gremlin/Chart.yaml
- gremlin/values.yaml
As it turns out, the `seLinuxOptions.type` does not incur relabeling of mounted files, and it should be the only field we need (at least in currently known cases)
> seLinuxOptions: clarify correct usage, add callout to bottlerocket

- gremlin/Chart.yaml
- gremlin/values.yaml
Without this, OpenShift will not authorize the gremlin DaemonSet to run.
```
Error creating: pods "gremlin-" is forbidden: unable to validate against any security context constraint: spec.volumes[2]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used
```
> hotfix: declare emptyDir in OpenShift SCC

- .github/workflows/unittest.yml
- .gitignore
- gremlin/.helmignore
- gremlin/templates/NOTES.txt
- gremlin/templates/_validation.tpl
- gremlin/tests/chao_deployment_test.yaml
- gremlin/tests/notes_test.yaml
To help gain confidence that future refactors will not completely break the chart, we should add unit testing to catch problems before they're merged.
> feat: Add unittests for Chao in the gremlin chart

- gremlin/Chart.yaml
- gremlin/README.md
- gremlin/templates/_validation.tpl
- gremlin/templates/daemonset.yaml
- gremlin/templates/gremlin-psp.yaml
- gremlin/tests/daemonset_test.yaml
- gremlin/tests/notes_test.yaml
- gremlin/values.yaml
Gremlin may need to resolve the hostnames of services defined in a cluster. For example, in order to access linkerd's destination api, our customer would have to patch their cluster with the following after a helm install:
```
kubectl patch daemonset/gremlin -n gremlin --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/dnsPolicy", "value":"ClusterFirstWithHostNet"}]'
```
Allow the gremlin daemonset's dns policy to be configurable so the patch is no longer necessary.  Default to `ClusterFirstWithHostNet` instead of `ClusterFirst` to resolve the hostnames of these services.
Tested without specifying the dnsPolicy (results in the default `ClusterFirstWithHostNet`):
```
$ helm install gremlin ./gremlin \
--namespace gremlin \
--set gremlin.secret.managed=true \
--set …
```
> Make dnsPolicy configurable

- gremlin/Chart.yaml
- gremlin/templates/gremlin-service-account.yaml
A rename in the cluster role binding was causing problems in upgrading from `0.21.0` to `0.22.0`.
Rename the cluster role binding to `gremlin-metadata-reader` from `gremlin`. Thanks to @philgebhardt and @thefirstofthe300 for help in sorting this out.
Installed `0.21.0`:
```bash
$ helm -n gremlin list
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
gremlin	gremlin  	2       	2025-05-05 14:20:40.110859 -0600 MDT	deployed	gremlin-0.21.0
```
Before (failed to upgrade to `0.22.0`):
```bash
$ helm upgrade gremlin gremlin/gremlin -n gremlin --version 0.22.0
Error: UPGRADE FAILED: cannot patch "gremlin" with kind ClusterRoleBinding: ClusterRoleBinding.rbac.authorization.k8s.io "gremlin" is invalid: roleRef: Invalid value: …
```
> Rename ClusterRoleBinding to gremlin-metadata-reader

- gremlin/Chart.yaml
- gremlin/templates/gremlin-service-account.yaml
- gremlin/tests/gremlin_service_account_test.yaml
- gremlin/values.yaml
* An upcoming gremlin release will have the ability to resolve ip-addresses for services by resolving EndpointSlices.
* When `discoverDestinationService` is enabled, we want to provide permissions for this resolver.
* Apply new permissions for new functionality only when the `discoverDestinationService` is enabled.
* Add unittest to ensure expected behavior
> discoverDestinationService: allow endpointslices for KubeResolver

- gremlin/Chart.yaml
- gremlin/templates/chao-service-account.yaml
* An upcoming gremlin release will have a new detected risk related to HorizontalPodAutoscaler(s)
* Apply new permission to allow reading information about HorizontalPodAutoscalers
> Add autoscaling read permissions
